spring:
  application:
    name: api-gateway
server:
  port: 18002
  instance:
    hostname: localhost
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:18001/eureka/

zuul:
  routes:
    billing-service: /billing-controller/**
